### ISSUE TITLE
Add reference to template in example.

### ISSUE THREAD

**Issue by richardgavel** [adr/madr#29]
In many CHANGELOG.md templates, there is a reference back to the template itself so that when I create a true instance of the CHANGELOG.md, someone can read it and know where to go to find the template it was created from to create another instance. I'd like to see this in the template for MADR.

See https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by koppor** [comment]
We decided to put it in `0000-use-markdown-architectural-decision-records.md`:

![grafik](https://user-images.githubusercontent.com/1366654/102141719-96f01b80-3e61-11eb-9667-74eefc8b7d85.png)

This seems not enough for you. You are asking for to put it in **each** ADR so that **each** markdown file contains a reference to MADR?

**Comment by koppor** [comment]
@richardgavel Do you mean like https://github.com/adr/madr/pull/30?

**Comment by richardgavel** [comment]
Yes
