### ISSUE TITLE
Most examples are still on template Version 2 (or older)

### ISSUE THREAD

**Issue by socadk** [adr/madr#90]

**Comment by socadk** [comment]
The jubilee blog post has an example: https://medium.com/olzzio/the-markdown-adr-madr-template-explained-and-distilled-b67603ec95bb, should we add it to repo? Feature all optional fields incl. validation?

**Comment by koppor** [comment]
Besides https://adr.github.io/madr/examples.html, this also includes our own ADRs at https://github.com/adr/madr/tree/develop/docs/decisions

**Comment by koppor** [comment]
Discussion:

- in a real-world project, long running, with dozens of ADRs, one would not update the old ADRs.
- consistency in our project - refs https://github.com/adr/madr/issues/122, https://github.com/adr/madr/issues/10

We want to make the used template versions of our real ADRs explicit in our repository, because maintaining examples in different versions is hard. Also, it is not important to show the past.
